### ISSUE TITLE
Please help.

### ISSUE THREAD

**Issue by partyp770** [OatmealDome/Geckiine#2]
Recently, whenever I have geckiine running, it takes a really long time to get back to the home menu. The same story goes for other applications. Im sure I entered the right ipv4 address.

**Comment by OatmealDome** [comment]
Do you have a cafiine server running on your computer?

**Comment by partyp770** [comment]
I solved the problem myself. I didnt realize that you needed a caffiine server running to get geckiine to load wara wara plaza.

**Comment by partyp770** [comment]
I was connecting to my wii u with a tpcgecko pc application.
