### ISSUE TITLE
5.5.2

### ISSUE THREAD

**Issue by NightScript370** [OatmealDome/Geckiine#3]
I'm just curious: Does this work on 5.5.2?

**Comment by OatmealDome** [comment]
Honestly, no idea. It would depend on what Nintendo changed in the update and I haven't looked into that at this point in time.

**Comment by partyp770** [comment]
Yes, it does. But its kind of a pain to run if you dont have Haxchi.

**Comment by OatmealDome** [comment]
I guess that answers your question then.
